name: Generate Random Addresses

on:
  push:
    tags:
      - 'v*'   # Trigger on tag pushes that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML page
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Deploy to GitHub Pages using native Git commands
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # If gh-pages branch exists, switch to it; if not, create it
          if git ls-remote --exit-code --heads origin gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          # Clean up existing files
          git rm -rf .

          # Move the new index.html into place (if not already at root)
          cp index.html .

          # Stage, commit, and force push the changes to gh-pages branch
          git add index.html
          git commit -m "Deploy updated random addresses"
          git push --force origin gh-pages
