on:
  push:
    branches:
      - main   # Rebuild when pushing changes to the main branch
    tags:
      - 'v*'   # Rebuild when pushing a new tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML page
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Deploy to GitHub Pages using native Git commands
        run: |
          # Configure Git for commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Run the script FIRST before switching branches
          chmod +x generate.sh
          ./generate.sh

          # Ensure index.html exists before proceeding
          if [ ! -f index.html ]; then
            echo "Error: index.html was not generated!"
            exit 1
          fi

          # Move index.html to a safe location before switching branches
          mv index.html /tmp/index.html

          # Fetch gh-pages branch to make sure it's available
          git fetch origin gh-pages || echo "gh-pages branch does not exist yet."

          # If gh-pages exists, switch to it; otherwise, create an orphan branch
          if git ls-remote --exit-code --heads origin gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          # Remove old files, but keep GitHub workflow configs
          git rm -rf . > /dev/null 2>&1 || true

          # Move the generated index.html back
          mv /tmp/index.html .

          # Add, commit, and push the changes
          git add index.html
          git commit -m "Deploy updated random addresses"
          git push --force origin gh-pages
