name: Generate and Deploy Random Addresses

on:
  push:
    branches:
      - main   # Rebuild when pushing changes to the main branch
    tags:
      - 'v*'   # Rebuild when pushing a new tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML page
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Deploy to GitHub Pages using native Git commands
        run: |
          # Configure Git for commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # If the gh-pages branch exists, switch to it, else create a new orphan branch
          if git ls-remote --exit-code --heads origin gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          # Remove existing files in gh-pages
          git rm -rf . > /dev/null 2>&1 || true

          # Copy the new index.html to the root
          cp index.html .

          # Stage and commit changes
          git add index.html
          git commit -m "Deploy updated random addresses"

          # Force push to update gh-pages branch
          git push --force origin gh-pages

